apiVersion: v1
kind: ConfigMap
metadata:
    name: web-server-config-{{ .Values.configVersions.webServer }}
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: web-server
        app.kubernetes.io/version: {{ .Values.configVersions.webServer }}
        app.kubernetes.io/part-of: fastapi-app
data:
    web_server_url: "http://web-server-service"
