apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-server
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: web-server
        app.kubernetes.io/part-of: fastapi-app
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: 2
    selector:
        matchLabels:
            app.kubernetes.io/name: web-server
    template:
        metadata:
            labels:
                app.kubernetes.io/name: web-server
        spec:
            containers:
                - name: web-server
                  image: "{{ .Values.webServer.image.repository }}:{{ .Values.webServer.image.tag }}"
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  env:
                    #   - name: REDIS_HOST
                    #     valueFrom:
                    #         configMapKeyRef:
                    #             name: redis-config-{{ .Values.configVersions.redis }}
                    #             key: hostname
                    #   - name: REDIS_PORT
                    #     valueFrom:
                    #         configMapKeyRef:
                    #             name: redis-config-{{ .Values.configVersions.redis }}
                    #             key: port
                    #   - name: REDIS_PASSWORD
                    #     valueFrom:
                    #         secretKeyRef:
                    #             name: redis-secret-{{ .Values.configVersions.redis }}
                    #             key: db_password
                      - name: MODEL_SERVER_URL_1
                        valueFrom:
                            configMapKeyRef:
                                name: timm-model-2-config-{{ .Values.configVersions.modelServer }}
                                key: model_server_url_1
                      - name: MODEL_SERVER_URL_2
                        valueFrom:
                            configMapKeyRef:
                                name: timm-model-2-config-{{ .Values.configVersions.modelServer }}
                                key: model_server_url_2



