apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mHemaAP/E2EMLOps_canary_argocd_kserve.git
    targetRevision: HEAD
    path: fastapi-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
